### ISSUE TITLE
please make LookupErrorKind public

### ISSUE THREAD

**Issue by miquels** [keeperofdakeys/dns-lookup#10]
`getnameinfo` and `getaddrinfo` return an error of type `LookupError`, which has a method `kind()` which returns a `LookupErrorKind` enum. Unfortunately, `LookupErrorKind` is not made public, so it cannot be used.

Please add `pub use err::LookupErrorKind` to lib.rs. Thanks :)

**Comment by keeperofdakeys** [comment]
Whoops, looks like that was an oversight on my part. I'll release a fix for this in the next few days.

**Comment by keeperofdakeys** [comment]
I've pushed a fix for this to git master, can you verify this does what you need? After that I'll push an update to creates.io.

**Comment by miquels** [comment]
Allright, this code now compiles: https://github.com/miquels/nntp-rs/commit/330fb122cc41a6edfd75e3aeaab19e6b8936684d

Thanks!

**Comment by keeperofdakeys** [comment]
Alright, I've pushed version 1.0.0 to crates.io. Thanks again for the bug report.
