### ISSUE TITLE
1.0.2 broke freebsd

### ISSUE THREAD

**Issue by rustysec** [keeperofdakeys/dns-lookup#13]
looks like commit `59e87439ea17116476fafed1e53627bee26779c3` is causing freebsd builds to fail, i haven't had time to put together a pr, but i probably can soon.

**Comment by Erk-** [comment]
Seems that it is missing in `libc` as far as I can tell from `man getnameinfo` FreeBSD does support it.

**Comment by Erk-** [comment]
I have made a pr to `libc` to fix the issue so we can wait for upstream to be merged.
https://github.com/rust-lang/libc/pull/1768

**Comment by keeperofdakeys** [comment]
Thanks for letting me know. In this case it's probably best to wait till this has been fixed upstream.

In the mean time it looks like Travis CI now has freebsd support (or will have). I'll have a look into getting this enabled on this repo. https://github.com/travis-ci/travis-build/pull/1780

**Comment by Erk-** [comment]
The reason it is failing is that `NI_NUMERICSERV` is not exposed to FreeBSD in `libc` which my patch above fixes. So it broke in the 59e87439 commit. I fixed it locally and it worked, but it seems I have to fix the patch up a bit so it does not fail on older versions of freebsd.

**Comment by Erk-** [comment]
This will be fixed with the next release of `libc` to use it now you can try out patching the dependency.
```toml
[patch.crates-io]
libc = { git = "https://github.com/rust-lang/libc.git" }
```

**Comment by keeperofdakeys** [comment]
I've added freebsd to travisci, so hopefully we'll catch any issues with freebsd in the future. Since the libc crate appears to be doing a release every few weeks I'll leave this open till the next release, and test/verify when its released.

If you need freebsd support now then hardcoding 1.0.1 is fine, the only feature packaged in 1.0.2 is the gethostname change.

**Comment by Erk-** [comment]
@keeperofdakeys The new version have been released so could I get you to rerun the tests and then close this if it works.

**Comment by keeperofdakeys** [comment]
Thanks, travisci is now passing. I've pushed 1.0.3 with no changes, because I don't actually know if crates.io enforces subversions or not. Either way it should be good now.
