### ISSUE TITLE
Remove dependency on libresolv for MacOS and IOS

### ISSUE THREAD

**Issue by arg0d** [keeperofdakeys/dns-lookup#14]
https://github.com/rust-lang/rust/issues/41570

Calling `libc::res_init();` on DNS failure creates a mandatory dependency requirement on `libresolv.tbd` for MacOS and IOS. Based on my testing this is not needed. I have created a test program to continuously make DNS request every second. Neither IOS nor MacOS versions have any problems when switching between different network modes (WIFI, Ethernet, Cellular).

Catting `/etc/resolv.conf` on MacOS gives the following output:
```
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 212.59.1.1
nameserver 8.8.8.8
```

**Comment by keeperofdakeys** [comment]
This behaviour is currently gated behind `#[cfg(unix)]` ([1](https://github.com/keeperofdakeys/dns-lookup/blob/master/src/lookup.rs#L28), [2](https://github.com/keeperofdakeys/dns-lookup/blob/master/src/lookup.rs#L54)). Changing this to `#[cfg(target_os = "linux")]` should be sufficient so it doesn't compile on OSX.

I'll push out a fix for this in a few days.

**Comment by arg0d** [comment]
I made a PR to exclude IOS and MacOS, as I wasn't sure if whether other unix-like OS are affected.

**Comment by keeperofdakeys** [comment]
I've now pushed a new version with the fix applied.
