### ISSUE TITLE
dns-lookup are failed to compile on Windows

### ISSUE THREAD

**Issue by bachue** [keeperofdakeys/dns-lookup#22]
Compiling dns-lookup v1.0.8
error[E0308]: mismatched types
  --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\dns-lookup-1.0.8\src\nameinfo.rs:47:9
   |
47 |         c_sock, c_sock_len,
   |         ^^^^^^ expected struct `SOCKADDR`, found struct `windows_sys::Windows::Win32::Networking::WinSock::SOCKADDR`
   |
   = note: expected raw pointer `*const SOCKADDR`
              found raw pointer `*const windows_sys::Windows::Win32::Networking::WinSock::SOCKADDR`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `dns-lookup` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by dilawar** [comment]
Came here to report exactly the same issue. Looks like `socket2` is not playing well with https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Networking/WinSock/struct.SOCKADDR.html# (or vice-versa). 

@bachue Please let me know if you find a way around it e.g. pinning versions.

**Comment by bachue** [comment]
@dilawar `socket2` v0.4.5 has been yanked.

**Comment by keeperofdakeys** [comment]
I might keep this issue open for now until socket2 have decided what they want to do, this crate may need changes if they release a new version. I'll also consider if I should switch to windows_sys myself (though it still appears to be quite new, and a fast moving target).

**Comment by keeperofdakeys** [comment]
I've done some testing on Windows and it all looks good, so I've pushed version 2.0.0 with the windows-sys changes.
