### ISSUE TITLE
Implement `FusedIterator` for `AddrInfoIter`.

### ISSUE THREAD

**Issue by kmkaplan** [keeperofdakeys/dns-lookup#31]
When exhausted `AddrInfoIter` always continues to yield `None`. Thus IWBNI it implemented `FusedIterator`.

**Comment by keeperofdakeys** [comment]
I can see how this would be adventagous, though this code is interfacing with nework traffic so Iterator optimisation isn't going to be a bottleneck (as far as I can see).

What's the correct way to implement this, the docs seem a little light. Replace `impl Iterator` with `impl FusedIterator` on AddrInfoIter? Or add a second, empty `impl FusedIterator` on AddrInfoIter as a marker trait?

**Comment by kmkaplan** [comment]
I believe the empty `impl FusedIterator` is the way to go. That's how it's done for [`Vec`](https://github.com/rust-lang/rust/blob/master/library/alloc/src/vec/into_iter.rs#L339) for example.

**Comment by keeperofdakeys** [comment]
Ah makes sense, thanks.
