### ISSUE TITLE
`failed to lookup address information: nodename nor servname provided, or not known`

### ISSUE THREAD

**Issue by tgross35** [keeperofdakeys/dns-lookup#32]
With a simple program on MacOs, I am running into the following problem:

```rust
fn main() {
    dbg!(dns_lookup::lookup_addr(&"192.168.150.220".parse().unwrap()));
}
```

output

```
[src/main.rs:2] dns_lookup::lookup_addr(&"192.168.150.220".parse().unwrap()) = Err(
    Custom {
        kind: Other,
        error: "failed to lookup address information: nodename nor servname provided, or not known",
    },
)
```

Is there any known solution?

**Comment by keeperofdakeys** [comment]
https://docs.rs/dns-lookup/latest/dns_lookup/fn.lookup_addr.html

This function returns an error when the record does not exist. In this case the reverse DNS entry for that IP is likely not known.

Could you confirm the entry with `dig -x 192.168.150.200` (I'm not a MacOS user, so use the appropriate tool if dig doesn't exist).

**Comment by keeperofdakeys** [comment]
If you're still having issues feel free to comment further, but I'll close this issue.
