### ISSUE TITLE
Why is the IP address obtained not a private address?

### ISSUE THREAD

**Issue by bin-ly** [keeperofdakeys/dns-lookup#34]
Why is the IP address obtained here a public address instead of a private address?

fn main() {
    let hostname = hostname::get()
        .expect("REASON")
        .to_string_lossy()
        .into_owned();
    let service = "ssh";
    let hints = AddrInfoHints {
        socktype: 2,
        flags: 0x0002,
        ..AddrInfoHints::default()
    };

    let sockets = getaddrinfo(Some(&hostname), Some(service), Some(hints))
        .unwrap()
        .collect::<std::io::Result<Vec<_>>>()
        .unwrap();
    for socket in sockets {
        println!("{:?}", socket.sockaddr.ip());   //69.167.164.199
    }
}

![image](https://github.com/keeperofdakeys/dns-lookup/assets/92200077/857b8624-37bb-40d9-848e-e3c93d83826e)

**Comment by keeperofdakeys** [comment]
Run "dig *hostname*", it should match what your program prints. Either its configured as a DNS record, or its in the /etc/hosts file.
