### ISSUE TITLE
host.docker.internal

### ISSUE THREAD

**Issue by zszep** [keeperofdakeys/dns-lookup#35]
On a windows 11 machine` lookup_addr `returns` host.docker.internal` as the host name.
Code:

```
let ip: IpAddr = "10.0.120.94".parse().unwrap();
let addr = lookup_addr(&ip).unwrap();
println!("ADRESA: {}", &addr);
```

When using `127.0.0.1` as the address I get `kubernetes.docker.internal `as the host name.
I do have docker installed but the machine name is wrong.

`gethostname() `returns the correct host name.

**Comment by keeperofdakeys** [comment]
Doing reverse DNS lookups on the systems IP will return whatever is in /etc/hosts, or defined in DNS. I'm guessing here its just getting the value from the OS.

So nothing is broken here.
