### ISSUE TITLE
Add gethostname()?

### ISSUE THREAD

**Issue by birkenfeld** [keeperofdakeys/dns-lookup#9]
I'm porting something from Python that uses `socket.getfqdn()`, which is basically `gethostbyaddr(gethostname())`. It would be nice to be able to do this with this crate as well, without having to fall back to libc.

**Comment by keeperofdakeys** [comment]
Considering that libc won't give you gethostname on windows, this sounds like a good idea. I'll have something up by the end of the week.

**Comment by keeperofdakeys** [comment]
I've pushed a new version with gethostname(). It should work on all platforms.
